export { default as Auth } from './Auth'
export { default as Dashboard } from './Dashboard'
export { default as DashHome } from './DashHome'
// export { default as Repayment } from './Repayment'

// In use
export { default as Enterprise } from './Enterprise'
export { default as Schools } from './Schools'
export { default as Events } from './Events'
export { default as Payments } from './Payments'
export { default as Jobs } from './Jobs'
export { default as Mentors } from './Mentors'
export { default as Alumini } from './Alumini'
export { default as GetInTouch } from './GetInTouch'
export { default as HigherEd } from './HigherEd'
export { default as CooperateTraining } from './CooperateTraining'
export { default as Applications } from './Applications'
